defaults_development: &defaults_development
  adapter:  mysql
  encoding: utf8
  host:     localhost
  username: structcomp
  password: 

development:
  database: sc_backbone_dev 
  <<: *defaults_development

production:
  database: structcomp
  <<: *defaults_development

test:
  database: structcompTest
  <<: *defaults_development

# cucumber:
#   database: structcompCucumberTest
#   <<: *defaults_development

