defaults_development: &defaults_development
  adapter:  mysql
  encoding: utf8
  host:     localhost
  username: root
  password: 

development:
  database: structcompDev
  <<: *defaults_development

production:
  database: structcomp
  <<: *defaults_development

test:
  database: structcompTest
  <<: *defaults_development

# cucumber:
#   database: structcompCucumberTest
#   <<: *defaults_development

